import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import MainNav from '@/components/MainNav'

const montserrat = Montserrat({
	variable: '--font-montserrat',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${montserrat.variable}  antialiased`}>
				<div className='flex'>
					<div className='hidden 2xl:flex w-[285px] h-screen bg-gray-800 text-slate-50'>
						<MainNav />
					</div>
					<div className='w-full max-w-[1130px] px-[15px] mx-auto bg-gray-800/10'>
						<header>header</header>
						<div>{children}</div>
					</div>
				</div>
			</body>
		</html>
	)
}
